### ISSUE TITLE
Декораторы для класса (вьюх)

### ISSUE THREAD

**Issue by Impish-** [Impish-/echoba#12]
@only_admin
@tornado.web.authenticated

**Comment by slykmp** [comment]
Ты об [этом](https://github.com/Impish-/echoba/commit/1b942d65ee3b59e39b1a7e095d92155fd6c2b53d)?

**Comment by Impish-** [comment]
Да только юзалось чтоб не на метод а на класс целиком
например:
@admin_only
class AddBoardHandler(BaseHandler):
    template_env = env
    template = 'add_board.html'
    form = AddBoardForm
    model = Board

```
def get(self, *args, **kwargs):
    self.render_template(form=self.form())

def post(self, *args, **kwargs):
    form = self.get_form()
    if form.validate():
        board = Board()
        form.populate_obj(board)
        board.add()
        return self.get()

    self.render_template(form=form)
```
