### ISSUE TITLE
Разделы

### ISSUE THREAD

**Issue by Impish-** [Impish-/echoba#15]

**Comment by slykmp** [comment]
В смылсе, убрать сквозную нумерацию? Посмотрел как на кусабе - там составной первичный ключ из полей <s>доносится печаль</s> id и boardid

**Comment by Impish-** [comment]
И это тоже но потом, Раздеты это типа тэгов(массивов из досок, [] lol ) пример [/a/, /b/ ,/d/] -  Разное [/g/, 'night'] -  тематике
