### ISSUE TITLE
Разметка

### ISSUE THREAD

**Issue by Impish-** [Impish-/echoba#21]
Если написать сообщение и среди него вставить %%сполер%% то сообщение пропадает почемуто

**Comment by slykmp** [comment]
Можешь полный текст написать, что отправлял. Я у себя проверял спойлеры

**Comment by Impish-** [comment]
Он не сохранился,  повторить не могу

**Comment by slykmp** [comment]
Попробовал "Текст со %%спойлером%% и без него". Свё нормально отработало

**Comment by Impish-** [comment]
Та же фигня,  не воспроизвести
