### ISSUE TITLE
Капча

### ISSUE THREAD

**Issue by Impish-** [Impish-/echoba#4]

**Comment by slykmp** [comment]
Так WTForms же рекапчу по умолчанию поддерживает

**Comment by Impish-** [comment]
Ну вот :)

**Comment by slykmp** [comment]
А не, ошибся чутка - из коробки рекапча поддерживается при установке Flask-WTF, если без обёртки ставить (как у нас), то ещё расширение [wtforms-recaptcha](https://pypi.python.org/pypi/wtforms-recaptcha) нужно доустанавливать

**Comment by slykmp** [comment]
Рано закрыл. Поддержка рекапчи в wtforms оказалась значительно хуже, чем я предполагал. Нормальная поддержка оказывается непосредственно во [flask-wtf](https://github.com/lepture/flask-wtf/tree/master/flask_wtf/recaptcha). Можно конечно, попробовать выцепить её оттуда, но у меня проблема с определением IP, поэтому она тоже не заработает (во flask-wtf использутся средства фласка)

**Comment by Impish-** [comment]
Ну я все равно формы перековыриваю;( Хочу изобразить более грамотную "session-strategy» думаю к понедельнику от меня коммиты будут, могу и капчу зацепить

**Comment by slykmp** [comment]
У меня локально завелась рекапча. Но в wftorms-recaptcha она старого образца, с текстом и требует Remote IP. В flask-wtf новая капча, в которой надо галочку поставить (и при странной или частой активности определить изображения по наличию в них указанного предмета). Думаю запариться и стырить из flask-wtf код, и отвязать от фласка

**Comment by Impish-** [comment]
Там поди филд+виджет уже готовые к тырингу  :)

**Comment by slykmp** [comment]
Да, почти. Просто завязка на фласк присутствует. Нужно будет пораскинуть мозгами, как в торнадо достать данные из POST-запроса в валидаторе

**Comment by Impish-** [comment]
class BaseHandler(RequestHandler):
...
def get_form(self, **kwargs):
        return self.form(self.request.arguments)
...
гипотетически вот так, self.get_form().captcha_field.data

**Comment by slykmp** [comment]
Не.
1. Данные о капче передаются в арументе g-recaptcha-response POST-запроса. captcha_field.data не канает.
2. я в текущем варианте (который не буду выкладывать, так как он вообще ломает отображение тредов) переопределял get_form() для BoardView, так как для wtforms-recaptcha нужно remote_ip передавать при определении экземпляра формы

**Comment by slykmp** [comment]
Как-то так сейчас:

``` python
def get_form(self, **kwargs):
    return self.form(self.request.arguments, captcha={'ip_address': self.request.remote_ip})
```

**Comment by Impish-** [comment]
я тут обнаружил https://github.com/BeardyBear/tornado-generic-handlers https://github.com/BeardyBear/tornado-generic-handlers, переводить все буду с понедельника, пока мало написанно

**Comment by slykmp** [comment]
Выглядит как фреймворк над фреймворком ))

**Comment by Impish-** [comment]
Аналог Django-CBV для торнады и скульалчеми)

**Comment by Impish-** [comment]
"Tornado along with SQLAlchemy and WTForms." ляпота

**Comment by slykmp** [comment]
Посмотрим, как оно на деле

**Comment by Impish-** [comment]
https://github.com/bosha/torhandlers https://github.com/bosha/torhandlers еще лучше

**Comment by slykmp** [comment]
[Как-то так](https://github.com/Impish-/echoba/commit/caf7119bbfa2a0ed10f26c35465ded85c313a595)

**Comment by slykmp** [comment]
Правда, в тредах валидация похоже вообще не работает
