### ISSUE TITLE
Верстка Доски

### ISSUE THREAD

**Issue by Impish-** [Impish-/echoba#7]

**Comment by slykmp** [comment]
Сейчас этим занимаюсь

**Comment by slykmp** [comment]
С macro воюю - оказывается, объекты нельзя передавать как аргументы

**Comment by slykmp** [comment]
А нет, документация говорит, что можно. Странно всё это

**Comment by Impish-** [comment]
Юзер стили будут ведь пахать?(как в кусабе)

**Comment by slykmp** [comment]
В смысле выбор стиля? Это js-ом реализуется, серверная сторона не важна

**Comment by slykmp** [comment]
Хотя можно и поддержку в движке запилить

**Comment by Impish-** [comment]
Ну я к тому чтобы «стандартные» стили (футабы там всякие) тоже присутствовали

**Comment by slykmp** [comment]
А вот это надо постараться

**Comment by slykmp** [comment]
Завтра посмотрю, попробую как можно точнее запилить, чтобы была совместимость. Нам бы ещё человека с куклоскриптом в тестеры))

**Comment by Impish-** [comment]
https://github.com/SthephanShinkufag/Dollchan-Extension-Tools

**Comment by slykmp** [comment]
Вроде основной функционал завёрстан. Пагинация интересно было бы видеть как в шаблоне должна выглядеть. Для главной лучше отдельную страницу пилить. Ну и в подвале непривычно мало всего. Формы удаления сообщений пока нет, ссылки на движок нет

**Comment by Impish-** [comment]
пагинация при прокрутке... но для «аналогового» варианта можно запилить «обычную»(список страниц), там в контексте секи переменные пагинатора

**Comment by slykmp** [comment]
Не подскажешь ссылочку на документацию, какие там переменные? Быстренько добавлю и спать пойду

**Comment by Impish-** [comment]
<a target="blank" href="https://github.com/BeardyBear/tornado-generic-handlers"> документации дифицит</a>

**Comment by Impish-** [comment]
[c1ce0a2](https://github.com/Impish-/echoba/commit/c1ce0a25e296badd315e22b9b1c88be0e667a390) редиректы

**Comment by slykmp** [comment]
Ок

**Comment by slykmp** [comment]
Что-то не получилось с наскока взять. Непонятно, где данные пагинатора - threads не определён, board.threads - обычный list

**Comment by Impish-** [comment]
> board.threads - обычный list

да это и есть 'threads' (уже отпагинированный список):)

**Comment by slykmp** [comment]
Но мне нужны текущая страница и количество страниц. [Здесь](https://github.com/BeardyBear/tornado-generic-handlers#pagination) эти данные есть, в шаблоне они недоступны

**Comment by slykmp** [comment]
Кстати, у меня сажа не работает

**Comment by Impish-** [comment]
page_obj тыкай

**Comment by Impish-** [comment]
> Кстати, у меня сажа не работает

щяс я с миграцией данных разберусь...

жахни 'print context' в get_context_data() там полный список объектов которые передаются в шаблон

**Comment by slykmp** [comment]
Количество страниц у нас в ....... paginator. Осталось остальное найти

**Comment by slykmp** [comment]
Текущая страница в page_obj))

**Comment by Impish-** [comment]
вангую:

<div class="pagination">
    <span class="step-links">
        {% if board.threads.has_previous %}
            <a href="{{ board.threads.previous_page_number }}/">previous</a>
        {% end %}
        <span class="current">
            Page {{ board.threads.number }} of {{ board.threads.paginator.num_pages }}.
        </span>
        {% if board.threads.has_next %}
            <a href="{{ board.threads.next_page_number }}/">next</a>
        {% end %}
    </span>
</div>

**Comment by slykmp** [comment]
нет

**Comment by Impish-** [comment]
Что может быть не так?

  File "/Users/Impish/PycharmProjects/ech/templates/board.html", line 2, in top-level template code
    {% from 'macro.html' import post_message %}
  File "/Users/Impish/PycharmProjects/ech/templates/base.html", line 32, in top-level template code
    {% block content %}
  File "/Users/Impish/PycharmProjects/ech/templates/board.html", line 17, in block "content"
    {{ post_message(
AttributeError: 'Message' object has no attribute '**call**'

**Comment by Impish-** [comment]
а все разобрался

**Comment by Impish-** [comment]
paginator._num_pages количество страниц

**Comment by slykmp** [comment]
Ладно, хрен с этими "вперёд"/"назад". Добавил просто номера страниц (если есть) https://github.com/Impish-/echoba/commit/9478b232f592418378721bb3c623f63205216d28

**Comment by slykmp** [comment]
Я спать - завтра на работу. Спокойной ночи

**Comment by Impish-** [comment]
Давай!
